### ISSUE TITLE
 load() method in class Configuration  is vulnerable

### ISSUE THREAD

**Issue by Joel-MalwareBenchmark** [bbengfort/confire#24]
class MyConfig(Configuration):
	mysetting = True
	logpath   = "/var/log/myapp.log"
	appname   = "MyApp"
settings = MyConfig.load()
#CONF_PATHS = [
#'/etc/confire.yaml',                    # The global configuration
#os.path.expanduser('~/.confire.yaml'),  # User specific configuration
#os.path.abspath('conf/confire.yaml')    # Local directory configuration]

#'~/.confire.yaml':!!python/object/apply:os.system ["calc.exe"]

Hi, there is a vulnerability in load() method in config.py, please see PoC above. It can execute arbitrary python commands resulting in command execution.

**Comment by bbengfort** [comment]
Thanks for your note this has been fixed in 8cc86a5

**Comment by laserlemon** [comment]
@bbengfort :wave: Hello! I'm on the GitHub team responsible for sending security alerts for vulnerable versions of Python libraries. I see that you have fix commits for this issue ([CVE-2017-16763](https://nvd.nist.gov/vuln/detail/CVE-2017-16763)) at 8cc86a5ec2327e070f1d576d61bbaadf861597ea and 70d3e3fe35afb87259a767f4b1f022a8694c113f on the `develop` and `master` branches, and that 2d52a5d6e219eb42d37daa3661a9ef86927df756 bumps the version to 0.3.0, but I don't see a corresponding version [in PyPI](https://pypi.org/project/confire/#history) nor a [release/tag](https://github.com/bbengfort/confire/releases).

We plan to alert users of `confire` for all current versions (`<= 0.2.0`) today and would like to offer remediation steps. If you're able, please release version 0.3.0 and we will delay our alerts until after the fix is released. Thank you! 👏
